# <center>《机器学习》— MindSpore 实践练习 </center>

### <center>姓名：XXX  学号：XXXXXXXXXXX</center>

# 14.基于mindspore实现MAXPooling层

## 14.1 采用mindspore.nn.MaxPool1d实现MAX Pooling层
Class mindspore.nn.MaxPool1d(kernel_size=1, stride=1, pad_mode='valid')


对时间数据进行最大池化运算。
在一个输入张量上应用1D max pooling，该张量可被视为一维平面的组合。
通常，输入的shape为 $\left(N_{i n}, C_{i n}, L_{i n}\right)$ ，MaxPool1d输出 $\left(L_{i n}\right)$ 维度区域最大值。给定 kernel_size 和 stride，公式如下:
$$
\operatorname{output}\left(N_i, C_j, l\right)=\max _{n=0, \ldots, \text { kernel_size-1 }} \operatorname{input}\left(N_i, C_j, \text { stride } \times l+n\right)
$$

In [7]:
import mindspore
import numpy as np
import mindspore.nn as nn
from mindspore import Tensor

    '''
    MaxPool1d(kernel_size,stride)
    '''
    #根据mindspore.nn.MaxPool1d定义补充代码

x = Tensor(np.random.randint(0, 10, [1, 2, 4]), mindspore.float32)
output = max_pool(x)
result = output.shape
print(result)

(1, 2, 2)


In [ ]:
#参考答案
max_pool = nn.MaxPool1d(kernel_size=3, stride=1)

## mindspore.nn.MaxPool2d
Class mindspore.nn.MaxPool2d(kernel_size=1, stride=1, pad_mode='valid', data_format='NCHW')

In [8]:
import mindspore
import numpy as np
import mindspore.nn as nn
from mindspore import Tensor

    '''
    nn.MaxPool2d(kernel_size,stride)
    '''
    #根据mindspore.nn.MaxPool2d定义补充代码

x = Tensor(np.random.randint(0, 10, [1, 2, 4, 4]), mindspore.float32)
output = pool(x)
print(output.shape)

(1, 2, 2, 2)


In [ ]:
#参考答案
pool = nn.MaxPool2d(kernel_size=3, stride=1)

## mindspore.ops.MaxPool
Class mindspore.ops.MaxPool(kernel_size=1, strides=1, pad_mode="valid", data_format="NCHW")

In [9]:
import mindspore
import numpy as np
import mindspore.ops as ops



x = Tensor(np.arange(1 * 3 * 3 * 4).reshape((1, 3, 3, 4)), mindspore.float32)
    '''
    ops.MaxPool(pad_mode, kernel_size, strides)
    '''
    #根据mindspore.ops.MaxPool定义补充代码

output = maxpool_op(x)
print(output)


[[[[ 5.  6.  7.]
   [ 9. 10. 11.]]

  [[17. 18. 19.]
   [21. 22. 23.]]

  [[29. 30. 31.]
   [33. 34. 35.]]]]


In [ ]:
#参考答案
maxpool_op = ops.MaxPool(pad_mode="VALID", kernel_size=2, strides=1)