# MAX Pooling

## mindspore.nn.MaxPool1d 
Class mindspore.nn.MaxPool1d(kernel_size=1, stride=1, pad_mode='valid')

In [7]:
import mindspore
import numpy as np
import mindspore.nn as nn
from mindspore import Tensor

    '''
    MaxPool1d(kernel_size,stride)
    '''

x = Tensor(np.random.randint(0, 10, [1, 2, 4]), mindspore.float32)
output = max_pool(x)
result = output.shape
print(result)

(1, 2, 2)


In [ ]:
#参考答案
max_pool = nn.MaxPool1d(kernel_size=3, stride=1)

## mindspore.nn.MaxPool2d
Class mindspore.nn.MaxPool2d(kernel_size=1, stride=1, pad_mode='valid', data_format='NCHW')

In [8]:
import mindspore
import numpy as np
import mindspore.nn as nn
from mindspore import Tensor

    '''
    nn.MaxPool2d(kernel_size,stride)
    '''

x = Tensor(np.random.randint(0, 10, [1, 2, 4, 4]), mindspore.float32)
output = pool(x)
print(output.shape)

(1, 2, 2, 2)


In [ ]:
#参考答案
pool = nn.MaxPool2d(kernel_size=3, stride=1)

## mindspore.ops.MaxPool
Class mindspore.ops.MaxPool(kernel_size=1, strides=1, pad_mode="valid", data_format="NCHW")

In [9]:
import mindspore
import numpy as np
import mindspore.ops as ops



x = Tensor(np.arange(1 * 3 * 3 * 4).reshape((1, 3, 3, 4)), mindspore.float32)
    '''
    ops.MaxPool(pad_mode, kernel_size, strides)
    '''

output = maxpool_op(x)
print(output)


[[[[ 5.  6.  7.]
   [ 9. 10. 11.]]

  [[17. 18. 19.]
   [21. 22. 23.]]

  [[29. 30. 31.]
   [33. 34. 35.]]]]


In [ ]:
maxpool_op = ops.MaxPool(pad_mode="VALID", kernel_size=2, strides=1)