# <center>《机器学习》— MindSpore 实践练习 </center>

### <center>姓名：XXX  学号：XXXXXXXXXXX</center>

# 14.基于mindspore实现MAX Pooling层

## 14.1 采用mindspore.nn.MaxPool1d实现MAX Pooling层
Class mindspore.nn.MaxPool1d(kernel_size=1, stride=1, pad_mode='valid')


对时间数据进行最大池化运算。
在一个输入张量上应用1D max pooling，该张量可被视为一维平面的组合。
通常，输入的shape为 $\left(N_{i n}, C_{i n}, L_{i n}\right)$ ，MaxPool1d输出 $\left(L_{i n}\right)$ 维度区域最大值。给定 kernel_size 和 stride，公式如下:
$$
\operatorname{output}\left(N_i, C_j, l\right)=\max _{n=0, \ldots, \text { kernel_size-1 }} \operatorname{input}\left(N_i, C_j, \text { stride } \times l+n\right)
$$

In [7]:
import mindspore
import numpy as np
import mindspore.nn as nn
from mindspore import Tensor


    '''
    MaxPool1d(kernel_size,stride)
    '''
    #根据mindspore.nn.MaxPool1d定义补充代码
x = Tensor(np.random.randint(0, 10, [1, 2, 4]), mindspore.float32)
output = max_pool(x)
result = output.shape
print(result)

(1, 2, 2)


In [ ]:
#答

## 14.2 采用mindspore.nn.MaxPool2d实现MAX Pooling层
Class mindspore.nn.MaxPool2d(kernel_size=1, stride=1, pad_mode='valid', data_format='NCHW')

对输入的多维数据进行二维的最大池化运算。
在一个输入Tensor上应用2D max pooling，可被视为组成一个 $2 D$ 平面。
通常，输入的形状为 $\left(N_{i n}, C_{i n}, H_{i n}, W_{i n}\right)$ ，MaxPool2d输出 $\left(H_{i n}, W_{i n}\right)$ 维度区域最大值。给定 kernel_size 为 $(k H, k W)$ 和 stride，公式如下。
$$
\operatorname{output}\left(N_i, C_j, h, w\right)=\max _{m=0, \ldots, k H-1} \max _{n=0, \ldots, k W-1} \operatorname{input}\left(N_i, C_j, \text { stride }[0] \times h+m, \text { stride }[1] \times w+n\right)
$$

In [8]:
import mindspore
import numpy as np
import mindspore.nn as nn
from mindspore import Tensor

    '''
    nn.MaxPool2d(kernel_size,stride)
    '''
    #根据mindspore.nn.MaxPool2d定义补充代码
x = Tensor(np.random.randint(0, 10, [1, 2, 4, 4]), mindspore.float32)
output = pool(x)
print(output.shape)

(1, 2, 2, 2)


In [ ]:
#答

## 14.3 采用mindspore.ops.MaxPool实现MAX Pooling层
Class mindspore.ops.MaxPool(kernel_size=1, strides=1, pad_mode="valid", data_format="NCHW")

对输入的多维数据进行二维的最大池化运算。
在一个输入 Tensor上应用 $2 D$ max pooling，可被视为 $2 D$ 输入平面。
通常，输入的shape为 $\left(N_{i n}, C_{i n}, H_{i n}, W_{i n}\right)$ ，MaxPool在 $\left(H_{i n}, W_{i n}\right)$ 维度输出区域最大值。给定 kernel_size 为 $(k H, k W)$ 和 stride，运算如下:
$$
\operatorname{output}\left(N_i, C_j, h, w\right)=\max _{m=0, \ldots, k H-1} \max _{n=0, \ldots, k W-1} \operatorname{input}\left(N_i, C_j, \text { stride }[0] \times h+m, \text { stride }[1] \times w+n\right)
$$

In [9]:
import mindspore
import numpy as np
import mindspore.ops as ops



x = Tensor(np.arange(1 * 3 * 3 * 4).reshape((1, 3, 3, 4)), mindspore.float32)
    '''
    ops.MaxPool(pad_mode, kernel_size, strides)
    '''
    #根据mindspore.ops.MaxPool定义补充代码
output = maxpool_op(x)
print(output)


[[[[ 5.  6.  7.]
   [ 9. 10. 11.]]

  [[17. 18. 19.]
   [21. 22. 23.]]

  [[29. 30. 31.]
   [33. 34. 35.]]]]


In [ ]:
#答