# Dropout

在2012年，Hinton在其论文《Improving neural networks by preventing co-adaptation of feature detectors》中提出Dropout。当一个复杂的前馈神经网络被训练在小的数据集时，容易造成过拟合。为了防止过拟合，可以通过阻止特征检测器的共同作用来提高神经网络的性能。

在2012年，Alex、Hinton在其论文《ImageNet Classification with Deep Convolutional Neural Networks》中用到了Dropout算法，用于防止过拟合。并且，这篇论文提到的AlexNet网络模型引爆了神经网络应用热潮，并赢得了2012年图像识别大赛冠军，使得CNN成为图像分类上的核心算法模型。

随后，又有一些关于Dropout的文章《Dropout:A Simple Way to Prevent Neural Networks from Overfitting》、《Improving Neural Networks with Dropout》、《Dropout as data augmentation》。

从上面的论文中，我们能感受到Dropout在深度学习中的重要性。那么，到底什么是Dropout呢？

Dropout可以作为训练深度神经网络的一种trick供选择。在每个训练批次中，通过忽略一半的特征检测器（让一半的隐层节点值为0），可以明显地减少过拟合现象。这种方式可以减少特征检测器（隐层节点）间的相互作用，检测器相互作用是指某些检测器依赖其他检测器才能发挥作用。

Dropout说的简单一点就是：我们在前向传播的时候，让某个神经元的激活值以一定的概率p停止工作，这样可以使模型泛化性更强，因为它不会太依赖某些局部的特征.

本小节主要介绍其在mindspore中的用法

In [1]:
from mindspore import nn

调用mindspore中的dropout函数，然后训练一个现有网络，得到一个结果。

In [2]:
import numpy as np
import mindspore as ms

x = ms.Tensor(np.ones([2, 2, 3]), ms.float32)
net = nn.Dropout(keep_prob=0.7)

# 执行训练
net.set_train()
output = net(x)
print("training result:\n", output)

# 执行推理
net.set_train(mode=False)
output = net(x)
print("\ninfer result:\n", output)

training result:
 [[[1.428173 0.       1.428173]
  [1.428173 0.       1.428173]]

 [[0.       1.428173 0.      ]
  [1.428173 1.428173 1.428173]]]

infer result:
 [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


[WARNING] DEVICE(97180,ffff87c13780,python):2022-11-25-11:57:02.561.694 [mindspore/ccsrc/plugin/device/ascend/hal/device/kernel_select_ascend.cc:330] FilterRaisedOrReducePrecisionMatchedKernelInfo] Operator:[Default/DropoutGenMask-op3] don't support int64, reduce precision from int64 to int32.
